# Generated by Django 6.0.3 on 2026-04-03 14:50

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registor_and_login', '0003_deliverypartner_is_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoNewsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('area', models.CharField(blank=True, max_length=100)),
                ('event_type', models.CharField(choices=[('flood', 'Flood'), ('high_rain', 'High Rain'), ('high_temperature', 'High Temperature'), ('strike', 'Strike'), ('protest', 'Protest'), ('curfew', 'Curfew'), ('disaster', 'Disaster')], max_length=32)),
                ('severity', models.CharField(choices=[('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe'), ('emergency', 'Emergency')], default='moderate', max_length=16)),
                ('headline', models.CharField(max_length=255)),
                ('summary', models.TextField(blank=True)),
                ('event_latitude', models.FloatField(blank=True, null=True)),
                ('event_longitude', models.FloatField(blank=True, null=True)),
                ('effective_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('source', models.CharField(default='demo-generator', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-effective_date', '-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PremiumAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('testing_bonus', models.DecimalField(decimal_places=2, default=Decimal('5000.00'), max_digits=12)),
                ('total_premium_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_payout_received', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('area', models.CharField(blank=True, max_length=100)),
                ('pincode', models.CharField(blank=True, max_length=10)),
                ('region', models.CharField(default='west', max_length=16)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('partner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='premium_account', to='registor_and_login.deliverypartner')),
            ],
        ),
        migrations.CreateModel(
            name='ClaimRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=64)),
                ('city', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=16)),
                ('crisis_level', models.CharField(choices=[('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe'), ('emergency', 'Emergency')], max_length=16)),
                ('status', models.CharField(choices=[('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('REJECTED_FRAUD', 'Rejected Fraud')], max_length=24)),
                ('final_score', models.FloatField(default=0.0)),
                ('weather_score', models.FloatField(default=0.0)),
                ('news_confidence', models.FloatField(default=0.0)),
                ('location_match', models.FloatField(default=0.0)),
                ('activity_drop', models.FloatField(default=0.0)),
                ('average_income_per_hour', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('expected_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('actual_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('loss_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('payout_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('notification_match', models.BooleanField(default=True)),
                ('cell_tower_verified', models.BooleanField(default=True)),
                ('motion_pattern_valid', models.BooleanField(default=True)),
                ('audit', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='registor_and_login.deliverypartner')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='premiumandclaims.premiumaccount')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PremiumLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('testing_bonus', 'Testing Bonus'), ('premium_debit', 'Premium Debit'), ('payout_credit', 'Payout Credit'), ('claim_rejected', 'Claim Rejected'), ('mock_payment', 'Mock Payment')], max_length=32)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('direction', models.CharField(default='credit', max_length=8)),
                ('status', models.CharField(choices=[('success', 'Success'), ('pending', 'Pending'), ('failed', 'Failed')], default='success', max_length=16)),
                ('reference', models.CharField(blank=True, max_length=64)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='premiumandclaims.premiumaccount')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyPremiumSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('week_end', models.DateField()),
                ('weekly_income', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_hours', models.DecimalField(decimal_places=2, max_digits=8)),
                ('weekend_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('category', models.CharField(max_length=16)),
                ('region', models.CharField(max_length=16)),
                ('weather_score', models.FloatField(default=0.0)),
                ('weather_multiplier', models.FloatField(default=1.0)),
                ('premium_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('deducted_on', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_premium_snapshots', to='registor_and_login.deliverypartner')),
            ],
            options={
                'ordering': ['-week_start', '-id'],
                'unique_together': {('partner', 'week_start')},
            },
        ),
    ]
