# Generated by Django 6.0.3 on 2026-04-02 12:16

import registor_and_login.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registor_and_login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverypartner',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=registor_and_login.models.profile_image_path),
        ),
    ]
