# Generated by Django 6.0.3 on 2026-04-02 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registor_and_login', '0002_alter_deliverypartner_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverypartner',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
