# Generated by Django 6.0.3 on 2026-04-03 06:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registor_and_login', '0003_deliverypartner_is_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateField(default=django.utils.timezone.localdate)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('start_latitude', models.FloatField(blank=True, null=True)),
                ('start_longitude', models.FloatField(blank=True, null=True)),
                ('start_verified', models.BooleanField(default=False)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('end_latitude', models.FloatField(blank=True, null=True)),
                ('end_longitude', models.FloatField(blank=True, null=True)),
                ('end_verified', models.BooleanField(default=False)),
                ('random_due_at', models.DateTimeField(blank=True, null=True)),
                ('random_time', models.DateTimeField(blank=True, null=True)),
                ('random_latitude', models.FloatField(blank=True, null=True)),
                ('random_longitude', models.FloatField(blank=True, null=True)),
                ('random_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registor_and_login.deliverypartner')),
            ],
        ),
    ]
