# Generated by Django 6.0.3 on 2026-04-03 14:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("work_sessions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SessionHistory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("history_date", models.DateField(default=django.utils.timezone.localdate)),
                ("total_earned_amount", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("total_working_hours", models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ("total_shifts", models.PositiveIntegerField(default=0)),
                ("order_names", models.JSONField(blank=True, default=list)),
                ("extracted_amounts", models.JSONField(blank=True, default=list)),
                ("raw_text", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "partner",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="registor_and_login.deliverypartner"),
                ),
            ],
            options={
                "unique_together": {("partner", "history_date")},
            },
        ),
    ]
