# Generated by Django 6.0.3 on 2026-04-03 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work_sessions', '0002_sessionhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessionhistory',
            name='order_names',
        ),
    ]
